### ISSUE TITLE
Unable to index/sortable an existing field

### ISSUE THREAD

**Issue by vikas-patel** [atelier-saulx/selva#32]
Hi,

I am a software developer at SportTotal Team. I updated the schema of 'updatedAt' field to make it sortable.
Old Schema:
module.exports = {
  type: 'timestamp',
}
New Schema:
module.exports = {
  type: 'timestamp',
  search: { type: ['NUMERIC', 'SORTABLE'] }
}

When I start the db service, which is expected to update the schema. I am getting following error.
12|db      | 2021-02-23T13:06:15: ---- error adding schema ----
12|db      | 2021-02-23T13:06:15: ReplyError: ERR Error running script (call to f_c545816098685cc5496530e85c8ac77be99fa5a2): @user_script:1089: user_script:1089: attempt to index field 'search' (a nil value) 
12|db      | 2021-02-23T13:06:15:     at parseError (/home/vikas/repos/v2/node_modules/redis-parser/lib/parser.js:193:12)
12|db      | 2021-02-23T13:06:15:     at parseType (/home/vikas/repos/v2/node_modules/redis-parser/lib/parser.js:303:14) {
12|db      | 2021-02-23T13:06:15:   command: 'EVALSHA',
12|db      | 2021-02-23T13:06:15:   args: [
12|db      | 2021-02-23T13:06:15:     'c545816098685cc5496530e85c8ac77be99fa5a2',
12|db      | 2021-02-23T13:06:15:     0,
12|db      | 2021-02-23T13:06:15:     'undefined:cb63e8d1-504c-4aac-a38c-ee40e7cea971',

@nfrade @youzi

**Comment by vikas-patel** [comment]
I can create a new sortable field but issue is with updating the schema of old field.
"updatedAt2": {
      "search": {
        "type": [
          "NUMERIC",
          "SORTABLE"
        ]
      },
      "type": "timestamp"
    },

Above new field, works fine.

**Comment by nfrade** [comment]
Hi Vikas,

You're changing a schema for a field but loading data from the backup that has data for that field using a different schema.
You need to migrate the data to the new schema.
This is specific to your project so we'll deal with this there.
