### ISSUE TITLE
Issue with Selva Observables when Cache is enabled

### ISSUE THREAD

**Issue by vikas-patel** [atelier-saulx/selva#35]
There's an issue with Selva Observables when Cache is enabled, although it works fine when when cache is set false. It seems issue with selva Diff.
Steps to reproduce:
1. Create a new poll.
2. Vote on video1 from chrome -> shows video1 100%
3. Open the poll page in another browser Firefox
4. Vote on video2 -> shows video1 50%, video2 50%
5. Switch back to Chrome Screen
6. Vote on video2 -> shows video2 100%
7. Vote on video1 -> shows video1 100%

Expected: video1 50% and video2 50%
Actual: It doesn't show the vote of another user vote (made in Firefox).

As a temporary fix, we have disabled the cache on poll observables.

**Comment by jimdebeer** [comment]
There is an update for selva diff that we probably need to use (hashes are updated to 64 bit instead of 32 so there is less collision)

**Comment by jimdebeer** [comment]
version is 1.0.17, vs 1.0.15
