### ISSUE TITLE
Empty record response when removing a key on a record

### ISSUE THREAD

**Issue by jimdebeer** [atelier-saulx/selva#462]
When removing a key on a record and the resulting record is `empty` the client will return null for the record

```javascript
await db.set({ myRecord: { field: { $delete: true } } })
console.log(await db.get({ myRecord: true }))
```
Will print `{ myRecord: null }`

What we want is `{ myRecord: {} }` even if its empty

**Comment by OlliV** [comment]
This works correctly in `selvad`. If something is still wrong it must be on the client side.
