### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by ansarizafar** [atelier-saulx/selva#83]
Selva looks amazing. What is the status of this project? Is it production ready? What are the hardware requirements to deploy Selva in production? Is it horizontally scale able?

**Comment by nfrade** [comment]
Hi @ansarizafar. Very much so. You should check [based](https://github.com/atelier-saulx/based). It's a developer platform built on top of selva, and it's built for scaling (and real-time). More info on the [website](https://based.io) and open beta coming soon.
